ln -sf "$HOME/github-repos/dotfiles/bashrc" "$HOME/.bashrc"
ln -sf "$HOME/github-repos/dotfiles/bash_profile" "$HOME/.bash_profile"
ln -sf "$HOME/github-repos/dotfiles/vimrc" "$HOME/.vimrc"
ln -sf "$HOME/github-repos/dotfiles/gitconfig" "$HOME/.gitconfig"
ln -sf "$HOME/github-repos/dotfiles/tmux.conf" "$HOME/.tmux.conf"
ln -sf "$HOME/github-repos/dotfiles/bootstrap" "$HOME/.bootstrap"
